### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Robert-instagram#1]
# Revisión - Aprobado
- [x] Estilo de código y limpieza
# Feedback
- ¡Muy buen trabajo @Roberttovarv , has hecho mucho más de lo que se te pedía . Felicidades!
## Estilo de código y limpieza
- ¡Muy bien hecho!
## Mejores prácticas/comentarios
-  En el styles.css, hay un error en el selector .IconosDer, debería ser .iconosDer .
- Tienes un pequeño problema con la agrupación de los iconos.
![Captura de pantalla de 2024-03-07 08-44-52](https://github.com/4GeeksAcademy/Robert-instagram/assets/139759297/26d3fea9-33f3-476b-bc8d-c62ba31231fc)
![Captura de pantalla de 2024-03-07 08-44-45](https://github.com/4GeeksAcademy/Robert-instagram/assets/139759297/495efc70-3b93-4601-8502-cc63b8781506)

**Comment by Roberttovarv** [comment]
Gracias, lo corregimos :)

**Comment by EduardoHernandezGuzman** [comment]
Muy buen trabajo Robert... a por el siguiente!!!
